version: "3.8"
services:
  backend:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    container_name: postgers
    ports:
          - 5432:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: